create extension if not exists pgcrypto;

create table if not exists public.familias (
  id bigint generated by default as identity primary key,
  codigo varchar(3) not null unique,
  nome varchar(150) not null,
  constraint familias_codigo_check check (codigo ~ '^[0-9]{3}$')
);

create table if not exists public.tipos (
  id bigint generated by default as identity primary key,
  familia_id bigint not null references public.familias(id) on delete restrict,
  codigo varchar(3) not null,
  nome varchar(150) not null,
  constraint tipos_codigo_check check (codigo ~ '^[0-9]{3}$'),
  constraint tipos_unique unique (familia_id, codigo)
);

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  sku varchar(13) not null unique,
  familia_codigo varchar(3) not null,
  tipo_codigo varchar(3) not null,
  sequencial integer not null,
  nome varchar(200) not null,
  descricao text,
  localizacao varchar(255) not null,
  quantidade integer not null default 0,
  estoque_minimo integer not null default 1,
  created_at timestamptz not null default now(),
  constraint produtos_sku_check check (sku ~ '^[0-9]{3}\.[0-9]{3}\.[0-9]{4}$'),
  constraint produtos_seq_check check (sequencial between 1 and 9999),
  constraint produtos_qtd_check check (quantidade >= 0),
  constraint produtos_min_check check (estoque_minimo >= 0)
);

create table if not exists public.historico_movimentacoes (
  id uuid primary key default gen_random_uuid(),
  produto_sku varchar(13) not null references public.produtos(sku) on delete restrict,
  tipo_movimentacao varchar(7) not null,
  quantidade integer not null,
  responsavel varchar(200) not null,
  motivo text,
  created_at timestamptz not null default now(),
  constraint historico_tipo_check check (tipo_movimentacao in ('ENTRADA','SAIDA')),
  constraint historico_qtd_check check (quantidade > 0)
);

create index if not exists idx_produtos_familia_tipo
on public.produtos(familia_codigo, tipo_codigo);

create index if not exists idx_historico_data
on public.historico_movimentacoes(created_at desc);

create or replace function public.criar_produto(
  p_familia_codigo varchar(3),
  p_tipo_codigo varchar(3),
  p_nome varchar(200),
  p_descricao text,
  p_localizacao varchar(255),
  p_quantidade integer,
  p_estoque_minimo integer
)
returns public.produtos
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_seq integer;
  v_produto public.produtos;
begin
  if not exists (select 1 from public.familias where codigo = p_familia_codigo) then
    raise exception 'Família não encontrada';
  end if;

  if not exists (
    select 1 from public.tipos t
    join public.familias f on f.id = t.familia_id
    where f.codigo = p_familia_codigo and t.codigo = p_tipo_codigo
  ) then
    raise exception 'Tipo não encontrado';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(p_familia_codigo || '.' || p_tipo_codigo, 0)
  );

  select coalesce(max(sequencial), 0) + 1 into v_seq
  from public.produtos
  where familia_codigo = p_familia_codigo
    and tipo_codigo = p_tipo_codigo;

  if v_seq > 9999 then
    raise exception 'Limite de 9999 produtos atingido';
  end if;

  insert into public.produtos(
    sku,familia_codigo,tipo_codigo,sequencial,nome,descricao,
    localizacao,quantidade,estoque_minimo
  )
  values(
    p_familia_codigo || '.' || p_tipo_codigo || '.' || lpad(v_seq::text,4,'0'),
    p_familia_codigo,p_tipo_codigo,v_seq,trim(p_nome),
    nullif(trim(p_descricao),''),trim(p_localizacao),
    p_quantidade,p_estoque_minimo
  )
  returning * into v_produto;

  return v_produto;
end;
$$;

create or replace function public.registrar_movimentacao(
  p_produto_sku varchar(13),
  p_tipo_movimentacao varchar(7),
  p_quantidade integer,
  p_responsavel varchar(200),
  p_motivo text default null
)
returns table(
  produto public.produtos,
  movimentacao public.historico_movimentacoes
)
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_produto public.produtos;
  v_mov public.historico_movimentacoes;
begin
  select * into v_produto
  from public.produtos
  where sku = p_produto_sku
  for update;

  if not found then raise exception 'Produto não encontrado'; end if;

  if p_tipo_movimentacao = 'SAIDA'
     and p_quantidade > v_produto.quantidade then
    raise exception 'Saldo insuficiente';
  end if;

  update public.produtos
  set quantidade = case
    when p_tipo_movimentacao = 'ENTRADA'
      then quantidade + p_quantidade
    else quantidade - p_quantidade
  end
  where sku = p_produto_sku
  returning * into v_produto;

  insert into public.historico_movimentacoes(
    produto_sku,tipo_movimentacao,quantidade,responsavel,motivo
  )
  values(
    p_produto_sku,p_tipo_movimentacao,p_quantidade,
    trim(p_responsavel),nullif(trim(p_motivo),'')
  )
  returning * into v_mov;

  return query select v_produto,v_mov;
end;
$$;

create or replace view public.relatorio_movimentacoes as
select h.id,h.produto_sku,p.nome as produto_nome,p.localizacao,
       h.tipo_movimentacao,h.quantidade,h.responsavel,h.motivo,h.created_at
from public.historico_movimentacoes h
join public.produtos p on p.sku = h.produto_sku
order by h.created_at desc;

create or replace view public.relatorio_estoque_baixo as
select sku,nome,localizacao,quantidade,estoque_minimo,created_at
from public.produtos
where quantidade <= estoque_minimo
order by quantidade asc,nome asc;

alter table public.familias enable row level security;
alter table public.tipos enable row level security;
alter table public.produtos enable row level security;
alter table public.historico_movimentacoes enable row level security;

drop policy if exists familias_select on public.familias;
drop policy if exists familias_insert on public.familias;
create policy familias_select on public.familias for select to anon,authenticated using (true);
create policy familias_insert on public.familias for insert to anon,authenticated with check (true);

drop policy if exists tipos_select on public.tipos;
drop policy if exists tipos_insert on public.tipos;
create policy tipos_select on public.tipos for select to anon,authenticated using (true);
create policy tipos_insert on public.tipos for insert to anon,authenticated with check (true);

drop policy if exists produtos_select on public.produtos;
create policy produtos_select on public.produtos for select to anon,authenticated using (true);

drop policy if exists historico_select on public.historico_movimentacoes;
create policy historico_select on public.historico_movimentacoes for select to anon,authenticated using (true);

grant usage on schema public to anon,authenticated;
grant select,insert on public.familias to anon,authenticated;
grant select,insert on public.tipos to anon,authenticated;
grant select on public.produtos to anon,authenticated;
grant select on public.historico_movimentacoes to anon,authenticated;

grant execute on function public.criar_produto(varchar,varchar,varchar,text,varchar,integer,integer)
to anon,authenticated;

grant execute on function public.registrar_movimentacao(varchar,varchar,integer,varchar,text)
to anon,authenticated;

grant select on public.relatorio_movimentacoes to anon,authenticated;
grant select on public.relatorio_estoque_baixo to anon,authenticated;
